import type {
  AuditLogEntry,
  DimensionSummary,
  GenericReportRow,
  ReportDimension,
  RevenueReportRow,
  RevenueTrendPoint,
} from '../types';

export const SEED_REVENUE_ROWS: RevenueReportRow[] = [
  {
    id: 'rev-1',
    period: 'Jul 2026 W1',
    department: 'OPD Consultation',
    grossRevenue: 1842500,
    gstCollected: 221100,
    deductions: 92400,
    netProfit: 1529000,
  },
  {
    id: 'rev-2',
    period: 'Jul 2026 W1',
    department: 'IPD Admissions',
    grossRevenue: 3260000,
    gstCollected: 391200,
    deductions: 163000,
    netProfit: 2705800,
  },
  {
    id: 'rev-3',
    period: 'Jul 2026 W1',
    department: 'Radiology & Imaging',
    grossRevenue: 978000,
    gstCollected: 117360,
    deductions: 48900,
    netProfit: 811740,
  },
  {
    id: 'rev-4',
    period: 'Jul 2026 W1',
    department: 'Laboratory Diagnostics',
    grossRevenue: 1245600,
    gstCollected: 149472,
    deductions: 62280,
    netProfit: 1033848,
  },
  {
    id: 'rev-5',
    period: 'Jul 2026 W1',
    department: 'Pharmacy Retail',
    grossRevenue: 2150000,
    gstCollected: 258000,
    deductions: 107500,
    netProfit: 1784500,
  },
  {
    id: 'rev-6',
    period: 'Jul 2026 W1',
    department: 'Surgical Services',
    grossRevenue: 4520000,
    gstCollected: 542400,
    deductions: 226000,
    netProfit: 3751600,
  },
];

export const SEED_REVENUE_TREND: RevenueTrendPoint[] = [
  { month: 'Feb', netProfit: 8420000 },
  { month: 'Mar', netProfit: 9150000 },
  { month: 'Apr', netProfit: 8890000 },
  { month: 'May', netProfit: 9620000 },
  { month: 'Jun', netProfit: 10140000 },
  { month: 'Jul', netProfit: 11616488 },
];

export const SEED_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-1',
    timestamp: '2026-07-09T14:22:18.000Z',
    userId: 'USR-ADM-0041',
    userRole: 'Administrator',
    componentChecked: 'Billing Engine',
    actionUndertaken: 'Invoice Override',
    impactValue: -12500,
  },
  {
    id: 'aud-2',
    timestamp: '2026-07-09T13:58:44.000Z',
    userId: 'USR-PHR-0112',
    userRole: 'Pharmacist',
    componentChecked: 'Inventory Ledger',
    actionUndertaken: 'Manual Stock Adjustment',
    impactValue: -340,
  },
  {
    id: 'aud-3',
    timestamp: '2026-07-09T13:41:07.000Z',
    userId: 'USR-LAB-0088',
    userRole: 'Lab Technician',
    componentChecked: 'Lab Results Queue',
    actionUndertaken: 'Result Revalidation',
    impactValue: 0,
  },
  {
    id: 'aud-4',
    timestamp: '2026-07-09T12:15:33.000Z',
    userId: 'USR-ADM-0041',
    userRole: 'Administrator',
    componentChecked: 'Access Control Matrix',
    actionUndertaken: 'Role Permission Grant',
    impactValue: 0,
  },
  {
    id: 'aud-5',
    timestamp: '2026-07-09T11:02:19.000Z',
    userId: 'USR-INV-0067',
    userRole: 'Store Manager',
    componentChecked: 'Procurement PO Module',
    actionUndertaken: 'PO Approval Bypass',
    impactValue: 890000,
  },
  {
    id: 'aud-6',
    timestamp: '2026-07-09T10:44:52.000Z',
    userId: 'USR-HR-0033',
    userRole: 'HR Manager',
    componentChecked: 'Payroll Disbursement',
    actionUndertaken: 'Salary Adjustment Entry',
    impactValue: 45000,
  },
  {
    id: 'aud-7',
    timestamp: '2026-07-09T09:30:11.000Z',
    userId: 'USR-PHR-0099',
    userRole: 'Pharmacist',
    componentChecked: 'Controlled Substance Vault',
    actionUndertaken: 'Dispense Audit Flag',
    impactValue: -1200,
  },
  {
    id: 'aud-8',
    timestamp: '2026-07-09T08:18:27.000Z',
    userId: 'USR-ADM-0022',
    userRole: 'Administrator',
    componentChecked: 'Patient EMR',
    actionUndertaken: 'Record Merge Operation',
    impactValue: 0,
  },
];

export const DIMENSION_SUMMARIES: Record<ReportDimension, DimensionSummary[]> = {
  patient: [
    { label: 'Total Registrations', value: '12,847', delta: '+4.2%', trend: 'up' },
    { label: 'Active IPD Census', value: '186', delta: '-2.1%', trend: 'down' },
    { label: 'Avg Length of Stay', value: '4.6 days', delta: '-0.3d', trend: 'up' },
    { label: 'Readmission Rate', value: '3.8%', delta: '+0.2%', trend: 'down' },
  ],
  revenue: [
    { label: 'Gross Revenue (MTD)', value: 'Γé╣1.40 Cr', delta: '+8.4%', trend: 'up' },
    { label: 'GST Collected', value: 'Γé╣16.8 L', delta: '+8.4%', trend: 'up' },
    { label: 'Total Deductions', value: 'Γé╣7.0 L', delta: '-1.2%', trend: 'up' },
    { label: 'Net Profit (MTD)', value: 'Γé╣1.16 Cr', delta: '+9.1%', trend: 'up' },
  ],
  inventory: [
    { label: 'SKUs Tracked', value: '2,418', delta: '+12', trend: 'neutral' },
    { label: 'Low Stock Alerts', value: '34', delta: '+5', trend: 'down' },
    { label: 'Stock Value', value: 'Γé╣2.84 Cr', delta: '+2.1%', trend: 'up' },
    { label: 'Variance (Last Audit)', value: 'Γé╣18,400', delta: '-42%', trend: 'up' },
  ],
  purchase: [
    { label: 'Open PRs', value: '28', delta: '-3', trend: 'up' },
    { label: 'POs Issued (MTD)', value: '64', delta: '+11', trend: 'up' },
    { label: 'Pending Approvals', value: '7', delta: '+2', trend: 'down' },
    { label: 'Procurement Spend', value: 'Γé╣48.2 L', delta: '+6.8%', trend: 'up' },
  ],
  doctor: [
    { label: 'Active Consultants', value: '142', delta: '+3', trend: 'up' },
    { label: 'Consultations (MTD)', value: '8,924', delta: '+5.6%', trend: 'up' },
    { label: 'Avg Wait Time', value: '18 min', delta: '-4 min', trend: 'up' },
    { label: 'No-Show Rate', value: '6.2%', delta: '-0.8%', trend: 'up' },
  ],
  lab: [
    { label: 'Tests Processed (MTD)', value: '14,682', delta: '+7.3%', trend: 'up' },
    { label: 'Critical Values Flagged', value: '89', delta: '+12', trend: 'down' },
    { label: 'TAT Compliance', value: '94.6%', delta: '+1.1%', trend: 'up' },
    { label: 'Revenue Contribution', value: 'Γé╣12.5 L', delta: '+4.9%', trend: 'up' },
  ],
  hr: [
    { label: 'Total Headcount', value: '1,248', delta: '+18', trend: 'up' },
    { label: 'Staff On Duty Now', value: '412', delta: 'Live', trend: 'neutral' },
    { label: 'Attendance Rate', value: '96.4%', delta: '+0.5%', trend: 'up' },
    { label: 'Payroll Disbursed', value: 'Γé╣3.82 Cr', delta: 'Jul Cycle', trend: 'neutral' },
  ],
  audit: [
    { label: 'Events (24h)', value: '847', delta: '+12%', trend: 'up' },
    { label: 'High-Impact Actions', value: '23', delta: '+4', trend: 'down' },
    { label: 'Override Attempts', value: '6', delta: '-2', trend: 'up' },
    { label: 'Compliance Score', value: '98.2%', delta: '+0.3%', trend: 'up' },
  ],
};

export const GENERIC_REPORT_ROWS: Record<
  Exclude<ReportDimension, 'revenue' | 'audit'>,
  GenericReportRow[]
> = {
  patient: [
    {
      id: 'pat-1',
      label: 'New Registrations',
      metric: 'OPD',
      value: '1,842',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pat-2',
      label: 'Discharges',
      metric: 'IPD',
      value: '312',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pat-3',
      label: 'Emergency Admissions',
      metric: 'ER',
      value: '478',
      status: 'Elevated',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pat-4',
      label: 'Insurance Claims Filed',
      metric: 'TPA',
      value: '956',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
  ],
  inventory: [
    {
      id: 'inv-1',
      label: 'Critical Low Stock',
      metric: 'Pharmacy',
      value: '18 SKUs',
      status: 'Alert',
      period: 'Jul 2026 W1',
    },
    {
      id: 'inv-2',
      label: 'Inter-Ward Transfers',
      metric: 'Stores',
      value: '142',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'inv-3',
      label: 'Expiry Within 30 Days',
      metric: 'Pharmacy',
      value: 'Γé╣2.4 L',
      status: 'Warning',
      period: 'Jul 2026 W1',
    },
    {
      id: 'inv-4',
      label: 'Audit Variance',
      metric: 'Central Store',
      value: 'Γé╣18,400',
      status: 'Review',
      period: 'Jun 2026',
    },
  ],
  purchase: [
    {
      id: 'pur-1',
      label: 'RFQs Sent',
      metric: 'Procurement',
      value: '22',
      status: 'Active',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pur-2',
      label: 'POs Closed',
      metric: 'Procurement',
      value: '38',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pur-3',
      label: 'Vendor SLA Breaches',
      metric: 'Vendor Hub',
      value: '3',
      status: 'Alert',
      period: 'Jul 2026 W1',
    },
    {
      id: 'pur-4',
      label: 'Three-Way Match Failures',
      metric: 'Finance',
      value: '5',
      status: 'Review',
      period: 'Jul 2026 W1',
    },
  ],
  doctor: [
    {
      id: 'doc-1',
      label: 'Top Performer',
      metric: 'Dr. Mehta ┬╖ Cardiology',
      value: '412 consults',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'doc-2',
      label: 'Highest Wait Queue',
      metric: 'Dr. Sharma ┬╖ Ortho',
      value: '47 min avg',
      status: 'Alert',
      period: 'Jul 2026 W1',
    },
    {
      id: 'doc-3',
      label: 'Procedure Volume',
      metric: 'Surgical Block B',
      value: '86 ops',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'doc-4',
      label: 'Referral Conversion',
      metric: 'Cross-Dept',
      value: '68.4%',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
  ],
  lab: [
    {
      id: 'lab-1',
      label: 'Hematology TAT',
      metric: 'Core Lab',
      value: '2.4 hrs avg',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'lab-2',
      label: 'Microbiology Backlog',
      metric: 'Culture Lab',
      value: '28 pending',
      status: 'Warning',
      period: 'Jul 2026 W1',
    },
    {
      id: 'lab-3',
      label: 'Critical Value Alerts',
      metric: 'All Sections',
      value: '89',
      status: 'Elevated',
      period: 'Jul 2026 W1',
    },
    {
      id: 'lab-4',
      label: 'Outsourced Tests',
      metric: 'Referral Lab',
      value: '156',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
  ],
  hr: [
    {
      id: 'hr-1',
      label: 'Overtime Hours',
      metric: 'Nursing',
      value: '1,248 hrs',
      status: 'Elevated',
      period: 'Jul 2026 W1',
    },
    {
      id: 'hr-2',
      label: 'Leave Requests Pending',
      metric: 'All Depts',
      value: '34',
      status: 'Normal',
      period: 'Jul 2026 W1',
    },
    {
      id: 'hr-3',
      label: 'New Hires',
      metric: 'HR Onboarding',
      value: '18',
      status: 'Normal',
      period: 'Jul 2026',
    },
    {
      id: 'hr-4',
      label: 'Attrition (YTD)',
      metric: 'Workforce',
      value: '4.2%',
      status: 'Normal',
      period: 'YTD 2026',
    },
  ],
};
