import type { LabOrder, LabTestDefinition } from '../types';

export const LAB_TEST_CATALOG: LabTestDefinition[] = [
  {
    code: 'HGB',
    name: 'Hemoglobin',
    unit: 'g/dL',
    refMin: 12.0,
    refMax: 16.0,
    criticalLow: 7.0,
    criticalHigh: 20.0,
  },
  {
    code: 'CREAT',
    name: 'Serum Creatinine',
    unit: 'mg/dL',
    refMin: 0.6,
    refMax: 1.2,
    criticalLow: 0.2,
    criticalHigh: 4.0,
  },
  {
    code: 'WBC',
    name: 'WBC Count',
    unit: '├ù10┬│/┬╡L',
    refMin: 4.0,
    refMax: 11.0,
    criticalLow: 2.0,
    criticalHigh: 30.0,
  },
  {
    code: 'PLT',
    name: 'Platelet Count',
    unit: '├ù10┬│/┬╡L',
    refMin: 150,
    refMax: 400,
    criticalLow: 50,
    criticalHigh: 600,
  },
  {
    code: 'GLU',
    name: 'Fasting Glucose',
    unit: 'mg/dL',
    refMin: 70,
    refMax: 100,
    criticalLow: 40,
    criticalHigh: 400,
  },
  {
    code: 'ALT',
    name: 'ALT (SGPT)',
    unit: 'U/L',
    refMin: 7,
    refMax: 56,
    criticalLow: 0,
    criticalHigh: 500,
  },
];

export function getTestByCode(code: string): LabTestDefinition | undefined {
  return LAB_TEST_CATALOG.find((t) => t.code === code);
}

export const SEED_LAB_ORDERS: LabOrder[] = [
  {
    id: 'lab-001',
    patientName: 'A.S.',
    uhid: 'NEX-2026-1001',
    orderedTests: ['CBC', 'Hemoglobin'],
    testCodes: ['HGB', 'WBC', 'PLT'],
    urgency: 'Urgent',
    status: 'pending_collection',
    results: [],
    orderedBy: 'Dr. Priya Menon',
    orderedAt: '2026-07-09T07:30:00Z',
  },
  {
    id: 'lab-002',
    patientName: 'R.K.',
    uhid: 'NEX-2026-1002',
    orderedTests: ['Renal Panel', 'Serum Creatinine'],
    testCodes: ['CREAT', 'GLU'],
    urgency: 'STAT',
    status: 'pending_collection',
    results: [],
    orderedBy: 'Dr. Arjun Das',
    orderedAt: '2026-07-09T08:00:00Z',
  },
  {
    id: 'lab-003',
    patientName: 'V.P.',
    uhid: 'NEX-2026-1003',
    orderedTests: ['LFT', 'ALT'],
    testCodes: ['ALT', 'GLU'],
    urgency: 'Routine',
    status: 'awaiting_results',
    barcode: 'NEX-LAB-99118',
    collectedAt: '2026-07-09T08:45:00Z',
    results: [],
    orderedBy: 'Dr. Priya Menon',
    orderedAt: '2026-07-09T07:00:00Z',
  },
  {
    id: 'lab-004',
    patientName: 'M.I.',
    uhid: 'NEX-2026-1004',
    orderedTests: ['CBC', 'Glucose'],
    testCodes: ['HGB', 'GLU'],
    urgency: 'Urgent',
    status: 'awaiting_results',
    barcode: 'NEX-LAB-99119',
    collectedAt: '2026-07-09T09:10:00Z',
    results: [],
    orderedBy: 'Dr. Lakshmi Nair',
    orderedAt: '2026-07-09T08:30:00Z',
  },
  {
    id: 'lab-005',
    patientName: 'S.R.',
    uhid: 'NEX-2026-1005',
    orderedTests: ['Renal Panel'],
    testCodes: ['CREAT'],
    urgency: 'Routine',
    status: 'pending_approval',
    barcode: 'NEX-LAB-99115',
    collectedAt: '2026-07-09T06:30:00Z',
    results: [
      { testCode: 'CREAT', value: 2.8, isCritical: true, alertLevel: 'critical' },
    ],
    orderedBy: 'Dr. Priya Menon',
    orderedAt: '2026-07-09T06:00:00Z',
    submittedAt: '2026-07-09T07:00:00Z',
  },
];
