import type { InternalTransfer, InventoryItem } from '../types';
import { generateTransferId } from '../types';

export const SEED_INVENTORY: InventoryItem[] = [
  {
    id: 'inv-med-001',
    category: 'Medicine Stock',
    itemName: 'Dolo 650 (Paracetamol)',
    sku: 'NEX-MED-1001',
    batchNumber: 'DL2026-A1',
    location: 'Central Warehouse',
    department: 'Pharmacy',
    quantityOnHand: 480,
    unit: 'Strips',
    expiryDate: '2027-06-15',
    safetyThreshold: 50,
  },
  {
    id: 'inv-med-002',
    category: 'Medicine Stock',
    itemName: 'Omez 20 (Omeprazole)',
    sku: 'NEX-MED-2001',
    batchNumber: 'OM2026-D2',
    location: 'Central Warehouse',
    department: 'Pharmacy',
    quantityOnHand: 38,
    unit: 'Strips',
    expiryDate: '2026-07-25',
    safetyThreshold: 40,
  },
  {
    id: 'inv-med-003',
    category: 'Medicine Stock',
    itemName: 'Insulin Glargine ΓÇö Lantus',
    sku: 'NEX-MED-4001',
    batchNumber: 'LT2026-H1',
    location: 'Pharmacy Store',
    department: 'Endocrinology',
    quantityOnHand: 22,
    unit: 'Vials',
    expiryDate: '2026-08-01',
    safetyThreshold: 20,
  },
  {
    id: 'inv-med-004',
    category: 'Medicine Stock',
    itemName: 'Amoxicillin 500mg ΓÇö Mox',
    sku: 'NEX-MED-3001',
    batchNumber: 'MX2026-F4',
    location: 'Central Warehouse',
    department: 'Pharmacy',
    quantityOnHand: 180,
    unit: 'Strips',
    expiryDate: '2026-06-20',
    safetyThreshold: 35,
  },
  {
    id: 'inv-eq-001',
    category: 'Capital Equipment',
    itemName: 'Portable Ventilator ΓÇö Hamilton C6',
    sku: 'NEX-EQ-5001',
    location: 'Biomedical Engineering',
    department: 'ICU',
    quantityOnHand: 4,
    unit: 'Units',
    safetyThreshold: 2,
    equipmentValue: 1850000,
  },
  {
    id: 'inv-eq-002',
    category: 'Capital Equipment',
    itemName: 'Infusion Pump ΓÇö B Braun Space',
    sku: 'NEX-EQ-5002',
    location: 'Biomedical Engineering',
    department: 'General Ward',
    quantityOnHand: 12,
    unit: 'Units',
    safetyThreshold: 6,
    equipmentValue: 420000,
  },
  {
    id: 'inv-eq-003',
    category: 'Capital Equipment',
    itemName: 'Defibrillator ΓÇö Philips HeartStart',
    sku: 'NEX-EQ-5003',
    location: 'Central Warehouse',
    department: 'Emergency',
    quantityOnHand: 3,
    unit: 'Units',
    safetyThreshold: 2,
    equipmentValue: 890000,
  },
  {
    id: 'inv-con-001',
    category: 'Clinical Consumables',
    itemName: 'Surgical Gloves ΓÇö Size M (Powder-free)',
    sku: 'NEX-CON-7001',
    batchNumber: 'SG2026-M1',
    location: 'Central Warehouse',
    department: 'OT Complex',
    quantityOnHand: 240,
    unit: 'Boxes',
    expiryDate: '2027-01-10',
    safetyThreshold: 50,
  },
  {
    id: 'inv-con-002',
    category: 'Clinical Consumables',
    itemName: 'IV Cannula 20G',
    sku: 'NEX-CON-7002',
    batchNumber: 'IV2026-C3',
    location: 'Central Warehouse',
    department: 'Emergency',
    quantityOnHand: 85,
    unit: 'Pieces',
    expiryDate: '2026-07-18',
    safetyThreshold: 100,
  },
  {
    id: 'inv-con-003',
    category: 'Clinical Consumables',
    itemName: 'Syringe 5ml (Disposable)',
    sku: 'NEX-CON-7003',
    batchNumber: 'SY2026-D8',
    location: 'Pharmacy Store',
    department: 'Laboratory',
    quantityOnHand: 1200,
    unit: 'Pieces',
    expiryDate: '2028-03-01',
    safetyThreshold: 200,
  },
  {
    id: 'inv-con-004',
    category: 'Clinical Consumables',
    itemName: 'Sterile Gauze Pads 10x10',
    sku: 'NEX-CON-7004',
    batchNumber: 'GZ2026-E2',
    location: 'Central Warehouse',
    department: 'ICU Nursing Station',
    quantityOnHand: 45,
    unit: 'Boxes',
    expiryDate: '2026-07-30',
    safetyThreshold: 60,
  },
];

export const SEED_TRANSFERS: InternalTransfer[] = [
  {
    id: generateTransferId(),
    itemId: 'inv-con-001',
    itemName: 'Surgical Gloves ΓÇö Size M (Powder-free)',
    batchNumber: 'SG2026-M1',
    sourceLocation: 'Central Warehouse',
    targetDepartment: 'OT Complex',
    quantity: 20,
    status: 'Pending',
    createdAt: '2026-07-09T08:00:00Z',
  },
  {
    id: generateTransferId(),
    itemId: 'inv-med-001',
    itemName: 'Dolo 650 (Paracetamol)',
    batchNumber: 'DL2026-A1',
    sourceLocation: 'Central Warehouse',
    targetDepartment: 'Emergency Department',
    quantity: 50,
    status: 'Pending',
    createdAt: '2026-07-09T09:15:00Z',
  },
];
