import type {
  PaymentLedgerRow,
  TrackedPO,
  VendorComplianceRecord,
  VendorPerformanceRow,
} from '../types';

export const VENDOR_OPTIONS = [
  { id: 'vnd-001', name: 'MedSupply India Pvt. Ltd.' },
  { id: 'vnd-002', name: 'PharmaLink Distributors' },
  { id: 'vnd-003', name: 'Surgical Hub Enterprises' },
  { id: 'vnd-004', name: 'SurgiCare Global' },
];

export const SEED_TRACKED_POS: TrackedPO[] = [
  {
    id: 'tpo-001',
    poNumber: 'PO-NEX-88421',
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    itemSummary: 'Omeprazole 20mg ΓÇö 300 Strips',
    deliveryStatus: 'Delivered',
    transitProgress: 100,
    lastUpdated: '2026-07-09T10:00:00Z',
  },
  {
    id: 'tpo-002',
    poNumber: 'PO-NEX-88398',
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    itemSummary: 'Syringe 5ml ΓÇö 1000 Pieces',
    deliveryStatus: 'In-Transit',
    transitProgress: 62,
    lastUpdated: '2026-07-09T11:30:00Z',
    eta: '2026-07-10T14:00:00Z',
  },
  {
    id: 'tpo-003',
    poNumber: 'PO-NEX-88375',
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    itemSummary: 'Sterile Gauze Pads ΓÇö 200 Boxes',
    deliveryStatus: 'PO Dispatched',
    transitProgress: 15,
    lastUpdated: '2026-07-09T09:45:00Z',
    eta: '2026-07-11T09:00:00Z',
  },
  {
    id: 'tpo-004',
    poNumber: 'PO-NEX-88360',
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    itemSummary: 'IV Cannula 20G ΓÇö 500 Pieces',
    deliveryStatus: 'At Loading Dock',
    transitProgress: 88,
    lastUpdated: '2026-07-09T11:55:00Z',
  },
  {
    id: 'tpo-005',
    poNumber: 'PO-NEX-88342',
    vendorId: 'vnd-003',
    vendorName: 'Surgical Hub Enterprises',
    itemSummary: 'Surgical Gloves ΓÇö 120 Boxes',
    deliveryStatus: 'Return Initiated',
    transitProgress: 40,
    lastUpdated: '2026-07-09T08:20:00Z',
  },
  {
    id: 'tpo-006',
    poNumber: 'PO-NEX-88320',
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    itemSummary: 'Insulin Glargine ΓÇö 50 Vials',
    deliveryStatus: 'In-Transit',
    transitProgress: 34,
    lastUpdated: '2026-07-09T11:00:00Z',
    eta: '2026-07-10T18:00:00Z',
  },
];

export const SEED_PERFORMANCE: VendorPerformanceRow[] = [
  {
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    fulfillmentRatePct: 96.2,
    avgLeadTimeDays: 3.4,
    costVariancePct: -1.2,
  },
  {
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    fulfillmentRatePct: 91.8,
    avgLeadTimeDays: 4.8,
    costVariancePct: 0.8,
  },
  {
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    fulfillmentRatePct: 98.5,
    avgLeadTimeDays: 2.1,
    costVariancePct: -2.4,
  },
  {
    vendorId: 'vnd-003',
    vendorName: 'Surgical Hub Enterprises',
    fulfillmentRatePct: 84.0,
    avgLeadTimeDays: 6.2,
    costVariancePct: 3.1,
  },
];

export const SEED_COMPLIANCE: VendorComplianceRecord[] = [
  {
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    medicalLicense: {
      label: 'Medical Device License',
      referenceId: 'MDL-KA-2024-8842',
      expiryDate: '2027-06-30',
      status: 'Active',
    },
    drugDistributionCert: {
      label: 'Drug Distribution Certificate',
      referenceId: 'DDC-CDSCO-7721',
      expiryDate: '2026-12-31',
      status: 'Compliant',
    },
    taxStatus: {
      label: 'GST Registration',
      referenceId: '29AABCM1234F1Z5',
      status: 'Active',
    },
  },
  {
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    medicalLicense: {
      label: 'Medical Device License',
      referenceId: 'MDL-MH-2023-4410',
      expiryDate: '2026-05-15',
      status: 'Expired',
    },
    drugDistributionCert: {
      label: 'Drug Distribution Certificate',
      referenceId: 'DDC-CDSCO-5590',
      expiryDate: '2027-03-20',
      status: 'Compliant',
    },
    taxStatus: {
      label: 'GST Registration',
      referenceId: '27AAACF5678G1Z2',
      status: 'Active',
    },
  },
  {
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    medicalLicense: {
      label: 'Medical Device License',
      referenceId: 'MDL-TN-2025-2201',
      expiryDate: '2028-01-15',
      status: 'Active',
    },
    drugDistributionCert: {
      label: 'Drug Distribution Certificate',
      referenceId: 'DDC-CDSCO-9012',
      expiryDate: '2027-08-10',
      status: 'Compliant',
    },
    taxStatus: {
      label: 'GST Registration',
      referenceId: '33AABCS7788H1Z9',
      status: 'Active',
    },
  },
  {
    vendorId: 'vnd-003',
    vendorName: 'Surgical Hub Enterprises',
    medicalLicense: {
      label: 'Medical Device License',
      referenceId: 'MDL-GJ-2022-1100',
      expiryDate: '2026-07-01',
      status: 'Expired',
    },
    drugDistributionCert: {
      label: 'Drug Distribution Certificate',
      referenceId: 'DDC-CDSCO-3344',
      expiryDate: '2026-09-30',
      status: 'Pending Review',
    },
    taxStatus: {
      label: 'GST Registration',
      referenceId: '24AABCS9012H1Z8',
      status: 'Active',
    },
  },
];

export const SEED_PAYMENT_LEDGER: PaymentLedgerRow[] = [
  {
    id: 'pay-001',
    vendorId: 'vnd-002',
    invoiceNumber: 'INV-PL-88421',
    poNumber: 'PO-NEX-88421',
    billAmount: 27552,
    threeWayMatchVerified: true,
    paymentStage: 'Settled',
    updatedAt: '2026-07-08T16:00:00Z',
  },
  {
    id: 'pay-002',
    vendorId: 'vnd-001',
    invoiceNumber: 'INV-MS-88398',
    poNumber: 'PO-NEX-88398',
    billAmount: 9520,
    threeWayMatchVerified: false,
    paymentStage: 'Awaiting Finance Release',
    updatedAt: '2026-07-09T09:00:00Z',
  },
  {
    id: 'pay-003',
    vendorId: 'vnd-004',
    invoiceNumber: 'INV-SC-88375',
    poNumber: 'PO-NEX-88375',
    billAmount: 32480,
    threeWayMatchVerified: true,
    paymentStage: 'Processing Gateway',
    updatedAt: '2026-07-09T10:30:00Z',
  },
  {
    id: 'pay-004',
    vendorId: 'vnd-001',
    invoiceNumber: 'INV-MS-88360',
    poNumber: 'PO-NEX-88360',
    billAmount: 10080,
    threeWayMatchVerified: true,
    paymentStage: 'Awaiting Finance Release',
    updatedAt: '2026-07-09T11:00:00Z',
  },
  {
    id: 'pay-005',
    vendorId: 'vnd-003',
    invoiceNumber: 'INV-SH-88342',
    poNumber: 'PO-NEX-88342',
    billAmount: 53016,
    threeWayMatchVerified: false,
    paymentStage: 'Awaiting Finance Release',
    updatedAt: '2026-07-09T08:30:00Z',
  },
  {
    id: 'pay-006',
    vendorId: 'vnd-002',
    invoiceNumber: 'INV-PL-88320',
    poNumber: 'PO-NEX-88320',
    billAmount: 142000,
    threeWayMatchVerified: true,
    paymentStage: 'Processing Gateway',
    updatedAt: '2026-07-09T11:45:00Z',
  },
];
