import type { MaintenanceTicket, MedicalAsset } from '../types';
import { generateTicketId } from '../types';

export const SEED_ASSETS: MedicalAsset[] = [
  {
    id: 'ast-001',
    assetId: 'NEX-AST-5001',
    name: 'Portable Ventilator ΓÇö Hamilton C6',
    department: 'ICU',
    manufacturer: 'Hamilton Medical',
    amcStatus: 'Active',
    amcRenewalDeadline: '2027-03-15',
    lastServiceDate: '2026-04-10',
    nextCalibrationDate: '2026-07-12',
    status: 'Operational',
  },
  {
    id: 'ast-002',
    assetId: 'NEX-AST-5002',
    name: 'Digital X-Ray Unit ΓÇö Siemens Multix',
    department: 'Radiology',
    manufacturer: 'Siemens Healthineers',
    amcStatus: 'Active',
    amcRenewalDeadline: '2026-12-01',
    lastServiceDate: '2026-06-01',
    nextCalibrationDate: '2026-07-15',
    status: 'Pending Calibration',
  },
  {
    id: 'ast-003',
    assetId: 'NEX-AST-5003',
    name: 'Infusion Pump ΓÇö B Braun Space',
    department: 'General Ward',
    manufacturer: 'B Braun',
    amcStatus: 'Active',
    amcRenewalDeadline: '2027-01-20',
    lastServiceDate: '2026-05-22',
    nextCalibrationDate: '2026-10-01',
    status: 'Operational',
  },
  {
    id: 'ast-004',
    assetId: 'NEX-AST-5004',
    name: 'Defibrillator ΓÇö Philips HeartStart',
    department: 'Emergency',
    manufacturer: 'Philips Healthcare',
    amcStatus: 'Expired',
    amcRenewalDeadline: '2026-05-30',
    lastServiceDate: '2026-03-15',
    nextCalibrationDate: '2026-07-08',
    status: 'Under Repair',
  },
  {
    id: 'ast-005',
    assetId: 'NEX-AST-5005',
    name: 'CT Scanner ΓÇö GE Revolution',
    department: 'Radiology',
    manufacturer: 'GE Healthcare',
    amcStatus: 'Active',
    amcRenewalDeadline: '2028-06-01',
    lastServiceDate: '2026-06-20',
    nextCalibrationDate: '2026-12-20',
    status: 'Operational',
  },
  {
    id: 'ast-006',
    assetId: 'NEX-AST-5006',
    name: 'Patient Monitor ΓÇö Mindray BeneVision',
    department: 'ICU',
    manufacturer: 'Mindray',
    amcStatus: 'Active',
    amcRenewalDeadline: '2027-02-28',
    lastServiceDate: '2026-06-05',
    nextCalibrationDate: '2026-07-10',
    status: 'Operational',
  },
  {
    id: 'ast-007',
    assetId: 'NEX-AST-5007',
    name: 'Anesthesia Workstation ΓÇö Dr├ñger Fabius',
    department: 'OT Complex',
    manufacturer: 'Dr├ñger',
    amcStatus: 'Active',
    amcRenewalDeadline: '2027-08-15',
    lastServiceDate: '2026-05-01',
    nextCalibrationDate: '2026-08-01',
    status: 'Operational',
  },
  {
    id: 'ast-008',
    assetId: 'NEX-AST-5008',
    name: 'Lab Analyzer ΓÇö Roche Cobas c311',
    department: 'Laboratory',
    manufacturer: 'Roche Diagnostics',
    amcStatus: 'Active',
    amcRenewalDeadline: '2027-04-01',
    lastServiceDate: '2026-06-28',
    nextCalibrationDate: '2026-07-14',
    status: 'Pending Calibration',
  },
];

export const SEED_TICKETS: MaintenanceTicket[] = [
  {
    id: generateTicketId(),
    assetId: 'ast-004',
    assetName: 'Defibrillator ΓÇö Philips HeartStart',
    urgency: 'Critical Breakdown',
    description: 'Unit fails self-test; shock delivery disabled alarm active.',
    reportedAt: '2026-07-09T07:00:00Z',
    status: 'In Progress',
  },
  {
    id: generateTicketId(),
    assetId: 'ast-002',
    assetName: 'Digital X-Ray Unit ΓÇö Siemens Multix',
    urgency: 'High',
    description: 'Calibration drift detected on exposure index.',
    reportedAt: '2026-07-08T14:30:00Z',
    status: 'Open',
  },
];
