import type {
  PurchaseOrder,
  PurchaseRequest,
  RFQ,
  VendorAnalyticsRow,
  VendorBid,
} from '../types';
import { generateId, generatePoNumber, generateRfqNumber } from '../types';

export const SEED_PURCHASE_REQUESTS: PurchaseRequest[] = [
  {
    id: 'pr-001',
    itemName: 'IV Cannula 20G ΓÇö Sterile',
    requestingDepartment: 'Emergency Department',
    quantity: 500,
    unit: 'Pieces',
    priority: 'Urgent',
    status: 'Pending',
    requestedAt: '2026-07-09T07:30:00Z',
  },
  {
    id: 'pr-002',
    itemName: 'Surgical Gloves ΓÇö Size M',
    requestingDepartment: 'OT Complex',
    quantity: 120,
    unit: 'Boxes',
    priority: 'Routine',
    status: 'Pending',
    requestedAt: '2026-07-09T08:15:00Z',
  },
  {
    id: 'pr-003',
    itemName: 'Portable Ventilator ΓÇö Hamilton C6',
    requestingDepartment: 'ICU',
    quantity: 2,
    unit: 'Units',
    priority: 'Urgent',
    status: 'Pending',
    requestedAt: '2026-07-09T09:00:00Z',
  },
  {
    id: 'pr-004',
    itemName: 'Paracetamol 650mg ΓÇö Dolo',
    requestingDepartment: 'Pharmacy',
    quantity: 200,
    unit: 'Strips',
    priority: 'Routine',
    status: 'Approved',
    requestedAt: '2026-07-08T14:00:00Z',
  },
];

const BIDS_IV_CANNULA: VendorBid[] = [
  {
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    unitPrice: 18,
    shippingDays: 3,
    gstPercent: 12,
    totalBidAmount: 10080,
    rating: 4.8,
  },
  {
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    unitPrice: 16.5,
    shippingDays: 5,
    gstPercent: 12,
    totalBidAmount: 9240,
    rating: 4.5,
  },
  {
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    unitPrice: 19,
    shippingDays: 2,
    gstPercent: 12,
    totalBidAmount: 10640,
    rating: 4.9,
  },
];

const BIDS_GLOVES: VendorBid[] = [
  {
    vendorId: 'vnd-003',
    vendorName: 'Surgical Hub Enterprises',
    unitPrice: 420,
    shippingDays: 4,
    gstPercent: 12,
    totalBidAmount: 56371,
    rating: 4.2,
  },
  {
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    unitPrice: 395,
    shippingDays: 3,
    gstPercent: 12,
    totalBidAmount: 53016,
    rating: 4.8,
  },
  {
    vendorId: 'vnd-005',
    vendorName: 'HealthPack Solutions',
    unitPrice: 410,
    shippingDays: 6,
    gstPercent: 12,
    totalBidAmount: 55027,
    rating: 4.6,
  },
];

export const SEED_RFQS: RFQ[] = [
  {
    id: 'rfq-001',
    rfqNumber: 'RFQ-NEX-4421',
    itemName: 'IV Cannula 20G ΓÇö Sterile',
    quantity: 500,
    unit: 'Pieces',
    department: 'Emergency Department',
    status: 'Bids Received',
    createdAt: '2026-07-08T10:00:00Z',
    bids: BIDS_IV_CANNULA,
  },
  {
    id: 'rfq-002',
    rfqNumber: 'RFQ-NEX-4398',
    itemName: 'Surgical Gloves ΓÇö Size M',
    quantity: 120,
    unit: 'Boxes',
    department: 'OT Complex',
    status: 'Bids Received',
    createdAt: '2026-07-07T11:30:00Z',
    bids: BIDS_GLOVES,
  },
  {
    id: 'rfq-003',
    rfqNumber: 'RFQ-NEX-4375',
    itemName: 'Insulin Glargine ΓÇö Lantus Solostar',
    quantity: 50,
    unit: 'Vials',
    department: 'Endocrinology',
    status: 'Open',
    createdAt: '2026-07-09T06:00:00Z',
    bids: [],
  },
];

export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-NEX-88421',
    rfqId: 'rfq-legacy-001',
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    itemName: 'Omeprazole 20mg ΓÇö Omez',
    quantity: 300,
    unit: 'Strips',
    unitPrice: 82,
    gstPercent: 12,
    totalAmount: 27552,
    status: 'Received',
    issuedAt: '2026-07-01T09:00:00Z',
    grnQuantity: 300,
    invoiceQuantity: 300,
    matchStatus: 'Matched',
  },
  {
    id: 'po-002',
    poNumber: 'PO-NEX-88398',
    rfqId: 'rfq-legacy-002',
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    itemName: 'Syringe 5ml (Disposable)',
    quantity: 1000,
    unit: 'Pieces',
    unitPrice: 8.5,
    gstPercent: 12,
    totalAmount: 9520,
    status: 'Received',
    issuedAt: '2026-07-03T14:00:00Z',
    grnQuantity: 980,
    invoiceQuantity: 1000,
    matchStatus: 'Mismatch',
  },
  {
    id: 'po-003',
    poNumber: 'PO-NEX-88375',
    rfqId: 'rfq-legacy-003',
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    itemName: 'Sterile Gauze Pads 10x10',
    quantity: 200,
    unit: 'Boxes',
    unitPrice: 145,
    gstPercent: 12,
    totalAmount: 32480,
    status: 'Issued',
    issuedAt: '2026-07-08T16:00:00Z',
    grnQuantity: 0,
    invoiceQuantity: 0,
    matchStatus: 'Pending',
  },
];

export const SEED_VENDOR_ANALYTICS: VendorAnalyticsRow[] = [
  {
    vendorId: 'vnd-001',
    vendorName: 'MedSupply India Pvt. Ltd.',
    totalPOs: 24,
    onTimeDeliveryPct: 96,
    avgRating: 4.8,
    totalSpend: 2840000,
    activeRFQs: 2,
  },
  {
    vendorId: 'vnd-002',
    vendorName: 'PharmaLink Distributors',
    totalPOs: 18,
    onTimeDeliveryPct: 91,
    avgRating: 4.5,
    totalSpend: 1920000,
    activeRFQs: 1,
  },
  {
    vendorId: 'vnd-004',
    vendorName: 'SurgiCare Global',
    totalPOs: 11,
    onTimeDeliveryPct: 98,
    avgRating: 4.9,
    totalSpend: 1450000,
    activeRFQs: 1,
  },
  {
    vendorId: 'vnd-003',
    vendorName: 'Surgical Hub Enterprises',
    totalPOs: 8,
    onTimeDeliveryPct: 84,
    avgRating: 4.2,
    totalSpend: 680000,
    activeRFQs: 1,
  },
];

export function createRfqFromRequest(pr: PurchaseRequest): RFQ {
  return {
    id: generateId('rfq'),
    rfqNumber: generateRfqNumber(),
    itemName: pr.itemName,
    quantity: pr.quantity,
    unit: pr.unit,
    department: pr.requestingDepartment,
    status: 'Open',
    createdAt: new Date().toISOString(),
    bids: [],
  };
}

export function createPoFromBid(rfq: RFQ, bid: VendorBid): PurchaseOrder {
  return {
    id: generateId('po'),
    poNumber: generatePoNumber(),
    rfqId: rfq.id,
    vendorId: bid.vendorId,
    vendorName: bid.vendorName,
    itemName: rfq.itemName,
    quantity: rfq.quantity,
    unit: rfq.unit,
    unitPrice: bid.unitPrice,
    gstPercent: bid.gstPercent,
    totalAmount: bid.totalBidAmount,
    status: 'Issued',
    issuedAt: new Date().toISOString(),
    grnQuantity: 0,
    invoiceQuantity: 0,
    matchStatus: 'Pending',
  };
}
