import type { PharmacyDispatchOrder, PharmacyInventoryItem } from '../types';
import { generateLineItemId } from '../types';

/** Live pharmacy stock with batch, expiry, and simulated pack barcodes */
export const SEED_PHARMACY_INVENTORY: PharmacyInventoryItem[] = [
  {
    medicineId: 'med-001',
    genericName: 'Paracetamol',
    brandName: 'Dolo 650',
    batchNumber: 'DL2026-A1',
    expiryDate: '2027-06',
    stockCount: 480,
    safetyThreshold: 50,
    barcode: 'NEX-PH-1001',
    unit: 'Strip',
  },
  {
    medicineId: 'med-001b',
    genericName: 'Paracetamol',
    brandName: 'Calpol 500',
    batchNumber: 'CP2026-B3',
    expiryDate: '2027-03',
    stockCount: 220,
    safetyThreshold: 40,
    barcode: 'NEX-PH-1002',
    unit: 'Strip',
  },
  {
    medicineId: 'med-001c',
    genericName: 'Paracetamol',
    brandName: 'Crocin Advance',
    batchNumber: 'CR2026-C7',
    expiryDate: '2026-12',
    stockCount: 95,
    safetyThreshold: 30,
    barcode: 'NEX-PH-1003',
    unit: 'Strip',
  },
  {
    medicineId: 'med-002',
    genericName: 'Omeprazole',
    brandName: 'Omez 20',
    batchNumber: 'OM2026-D2',
    expiryDate: '2027-08',
    stockCount: 310,
    safetyThreshold: 40,
    barcode: 'NEX-PH-2001',
    unit: 'Strip',
  },
  {
    medicineId: 'med-002b',
    genericName: 'Omeprazole',
    brandName: 'Omez-D',
    batchNumber: 'OD2026-E1',
    expiryDate: '2027-01',
    stockCount: 140,
    safetyThreshold: 25,
    barcode: 'NEX-PH-2002',
    unit: 'Strip',
  },
  {
    medicineId: 'med-003',
    genericName: 'Amoxicillin',
    brandName: 'Mox 500',
    batchNumber: 'MX2026-F4',
    expiryDate: '2026-11',
    stockCount: 180,
    safetyThreshold: 35,
    barcode: 'NEX-PH-3001',
    unit: 'Strip',
  },
  {
    medicineId: 'med-003b',
    genericName: 'Amoxicillin',
    brandName: 'Novamox 500',
    batchNumber: 'NV2026-G2',
    expiryDate: '2027-02',
    stockCount: 92,
    safetyThreshold: 30,
    barcode: 'NEX-PH-3002',
    unit: 'Strip',
  },
  {
    medicineId: 'med-004',
    genericName: 'Insulin Glargine',
    brandName: 'Lantus Solostar',
    batchNumber: 'LT2026-H1',
    expiryDate: '2026-09',
    stockCount: 22,
    safetyThreshold: 20,
    barcode: 'NEX-PH-4001',
    unit: 'Vial',
  },
  {
    medicineId: 'med-005',
    genericName: 'Azithromycin',
    brandName: 'Azithral 500',
    batchNumber: 'AZ2026-I3',
    expiryDate: '2027-04',
    stockCount: 64,
    safetyThreshold: 20,
    barcode: 'NEX-PH-5001',
    unit: 'Strip',
  },
  {
    medicineId: 'med-005b',
    genericName: 'Azithromycin',
    brandName: 'Zithromax 500',
    batchNumber: 'ZT2026-J2',
    expiryDate: '2026-10',
    stockCount: 38,
    safetyThreshold: 15,
    barcode: 'NEX-PH-5002',
    unit: 'Strip',
  },
];

export function getInventoryByMedicineId(medicineId: string): PharmacyInventoryItem | undefined {
  return SEED_PHARMACY_INVENTORY.find((i) => i.medicineId === medicineId);
}

export function getAlternativesForGeneric(
  genericName: string,
  excludeMedicineId?: string,
): PharmacyInventoryItem[] {
  return SEED_PHARMACY_INVENTORY.filter(
    (i) => i.genericName === genericName && i.medicineId !== excludeMedicineId,
  );
}

/** Incoming EMR consultation prescriptions awaiting pharmacy verification */
export const SEED_PHARMACY_ORDERS: PharmacyDispatchOrder[] = [
  {
    id: 'phr-001',
    encounterId: 'enc-seed-001',
    patientName: 'A.S.',
    uhid: 'NEX-2026-1001',
    prescribingDoctor: 'Dr. Priya Menon',
    receivedAt: '2026-07-09T10:15:00Z',
    status: 'Pending Verification',
    lineItems: [
      {
        id: generateLineItemId(),
        medicineId: 'med-001',
        genericName: 'Paracetamol',
        brandName: 'Dolo 650',
        dosage: '650 mg',
        frequency: '1-0-1 (BD)',
        duration: '5 days',
        quantity: 10,
        verified: false,
      },
      {
        id: generateLineItemId(),
        medicineId: 'med-002',
        genericName: 'Omeprazole',
        brandName: 'Omez 20',
        dosage: '20 mg',
        frequency: '1-0-0 (OD)',
        duration: '14 days',
        quantity: 14,
        verified: false,
      },
    ],
  },
  {
    id: 'phr-002',
    encounterId: 'enc-seed-002',
    patientName: 'R.K.',
    uhid: 'NEX-2026-1002',
    prescribingDoctor: 'Dr. Arjun Das',
    receivedAt: '2026-07-09T10:42:00Z',
    status: 'Pending Verification',
    lineItems: [
      {
        id: generateLineItemId(),
        medicineId: 'med-003',
        genericName: 'Amoxicillin',
        brandName: 'Mox 500',
        dosage: '500 mg',
        frequency: '1-1-1 (TID)',
        duration: '7 days',
        quantity: 21,
        verified: false,
      },
      {
        id: generateLineItemId(),
        medicineId: 'med-005',
        genericName: 'Azithromycin',
        brandName: 'Azithral 500',
        dosage: '500 mg',
        frequency: '1-0-0 (OD)',
        duration: '3 days',
        quantity: 3,
        verified: false,
      },
    ],
  },
  {
    id: 'phr-003',
    encounterId: 'enc-seed-003',
    patientName: 'V.P.',
    uhid: 'NEX-2026-1003',
    prescribingDoctor: 'Dr. Priya Menon',
    receivedAt: '2026-07-09T11:05:00Z',
    status: 'Partially Dispensed',
    lineItems: [
      {
        id: generateLineItemId(),
        medicineId: 'med-004',
        genericName: 'Insulin Glargine',
        brandName: 'Lantus Solostar',
        dosage: '10 units',
        frequency: '0-0-1 (HS)',
        duration: '1 month',
        quantity: 5,
        verified: true,
      },
      {
        id: generateLineItemId(),
        medicineId: 'med-002',
        genericName: 'Omeprazole',
        brandName: 'Omez 20',
        dosage: '20 mg',
        frequency: '1-0-0 (OD)',
        duration: '10 days',
        quantity: 10,
        verified: false,
      },
    ],
  },
  {
    id: 'phr-004',
    encounterId: 'enc-seed-004',
    patientName: 'M.I.',
    uhid: 'NEX-2026-1004',
    prescribingDoctor: 'Dr. Lakshmi Nair',
    receivedAt: '2026-07-09T09:20:00Z',
    status: 'Completed',
    dispensedAt: '2026-07-09T09:35:00Z',
    lineItems: [
      {
        id: generateLineItemId(),
        medicineId: 'med-001',
        genericName: 'Paracetamol',
        brandName: 'Dolo 650',
        dosage: '650 mg',
        frequency: '1-0-0 (OD)',
        duration: '3 days',
        quantity: 3,
        verified: true,
      },
    ],
  },
];
