import type { DayKey, Employee, WeeklyRotaEntry } from '../types';

export const SEED_EMPLOYEES: Employee[] = [
  {
    id: 'emp-001',
    staffId: 'NEX-HR-1001',
    name: 'Priya Venkatesh',
    role: 'Billing Executive',
    department: 'Finance',
    activeShift: 'Morning Shift ΓÇö Billing Counter',
    status: 'On Duty',
    baseSalary: 42000,
    shiftsCompleted: 22,
    lopDays: 0,
    bonusModifierPct: 5,
    taxDeductions: 4200,
  },
  {
    id: 'emp-002',
    staffId: 'NEX-HR-1002',
    name: 'Dr. Priya Menon',
    role: 'Doctor / Consultant',
    department: 'Cardiology',
    activeShift: 'Morning Shift ΓÇö OPD Block A',
    status: 'On Duty',
    baseSalary: 185000,
    shiftsCompleted: 20,
    lopDays: 0,
    bonusModifierPct: 12,
    taxDeductions: 28000,
  },
  {
    id: 'emp-003',
    staffId: 'NEX-HR-1003',
    name: 'Anita Desai',
    role: 'Staff Nurse',
    department: 'ICU',
    activeShift: 'Night Shift ΓÇö ICU Ward',
    status: 'On Duty',
    baseSalary: 38000,
    shiftsCompleted: 24,
    lopDays: 1,
    bonusModifierPct: 8,
    taxDeductions: 3600,
  },
  {
    id: 'emp-004',
    staffId: 'NEX-HR-1004',
    name: 'Ravi Shankar',
    role: 'Lab Technician',
    department: 'Laboratory',
    activeShift: 'Evening Shift ΓÇö LIS',
    status: 'On Duty',
    baseSalary: 35000,
    shiftsCompleted: 21,
    lopDays: 0,
    bonusModifierPct: 4,
    taxDeductions: 3200,
  },
  {
    id: 'emp-005',
    staffId: 'NEX-HR-1005',
    name: 'Karan Mehta',
    role: 'Radiologist',
    department: 'Radiology',
    activeShift: 'Morning Shift ΓÇö PACS Suite',
    status: 'Off Duty',
    baseSalary: 165000,
    shiftsCompleted: 18,
    lopDays: 0,
    bonusModifierPct: 10,
    taxDeductions: 24000,
  },
  {
    id: 'emp-006',
    staffId: 'NEX-HR-1006',
    name: 'Sunita Rao',
    role: 'Pharmacist',
    department: 'Pharmacy',
    activeShift: 'Evening Shift ΓÇö Dispensing',
    status: 'On Duty',
    baseSalary: 40000,
    shiftsCompleted: 23,
    lopDays: 0,
    bonusModifierPct: 6,
    taxDeductions: 4000,
  },
  {
    id: 'emp-007',
    staffId: 'NEX-HR-1007',
    name: 'Meera Iyer',
    role: 'Receptionist',
    department: 'Front Office',
    activeShift: 'Morning Shift ΓÇö Registration',
    status: 'On Leave',
    baseSalary: 28000,
    shiftsCompleted: 15,
    lopDays: 3,
    bonusModifierPct: 0,
    taxDeductions: 2100,
  },
  {
    id: 'emp-008',
    staffId: 'NEX-HR-1008',
    name: 'Arjun Das',
    role: 'Hospital Administrator',
    department: 'Administration',
    activeShift: 'Morning Shift ΓÇö Command Center',
    status: 'On Duty',
    baseSalary: 95000,
    shiftsCompleted: 22,
    lopDays: 0,
    bonusModifierPct: 15,
    taxDeductions: 14000,
  },
  {
    id: 'emp-009',
    staffId: 'NEX-HR-1009',
    name: 'Lakshmi Nair',
    role: 'HR Manager',
    department: 'Human Resources',
    activeShift: 'Morning Shift ΓÇö HR Desk',
    status: 'On Duty',
    baseSalary: 72000,
    shiftsCompleted: 22,
    lopDays: 0,
    bonusModifierPct: 8,
    taxDeductions: 9800,
  },
  {
    id: 'emp-010',
    staffId: 'NEX-HR-1010',
    name: 'Vikram Singh',
    role: 'Security & Facilities',
    department: 'Operations',
    activeShift: 'Night Shift ΓÇö Perimeter',
    status: 'On Duty',
    baseSalary: 26000,
    shiftsCompleted: 26,
    lopDays: 0,
    bonusModifierPct: 3,
    taxDeductions: 1800,
  },
  {
    id: 'emp-011',
    staffId: 'NEX-HR-1011',
    name: 'Deepa Krishnan',
    role: 'Procurement Officer',
    department: 'Supply Chain',
    activeShift: 'Morning Shift ΓÇö Procurement Hub',
    status: 'Off Duty',
    baseSalary: 48000,
    shiftsCompleted: 20,
    lopDays: 1,
    bonusModifierPct: 7,
    taxDeductions: 5200,
  },
  {
    id: 'emp-012',
    staffId: 'NEX-HR-1012',
    name: 'Rajesh Kumar',
    role: 'Staff Nurse',
    department: 'Emergency',
    activeShift: 'Night Shift ΓÇö Emergency',
    status: 'On Duty',
    baseSalary: 36000,
    shiftsCompleted: 25,
    lopDays: 0,
    bonusModifierPct: 10,
    taxDeductions: 3400,
  },
];

function rota(
  employeeId: string,
  days: Record<DayKey, WeeklyRotaEntry['days'][DayKey]>,
): WeeklyRotaEntry {
  return { employeeId, days };
}

export const SEED_ROTA: WeeklyRotaEntry[] = [
  rota('emp-001', { mon: 'Morning', tue: 'Morning', wed: 'Morning', thu: 'Weekly Off', fri: 'Morning', sat: 'Morning', sun: 'Weekly Off' }),
  rota('emp-002', { mon: 'Morning', tue: 'Morning', wed: 'Weekly Off', thu: 'Morning', fri: 'Morning', sat: 'Weekly Off', sun: 'Weekly Off' }),
  rota('emp-003', { mon: 'Night', tue: 'Night', wed: 'Weekly Off', thu: 'Night', fri: 'Night', sat: 'Night', sun: 'Weekly Off' }),
  rota('emp-004', { mon: 'Evening', tue: 'Evening', wed: 'Evening', thu: 'Weekly Off', fri: 'Evening', sat: 'Evening', sun: 'Weekly Off' }),
  rota('emp-005', { mon: 'Morning', tue: 'Weekly Off', wed: 'Morning', thu: 'Morning', fri: 'Weekly Off', sat: 'Morning', sun: 'Weekly Off' }),
  rota('emp-006', { mon: 'Evening', tue: 'Evening', wed: 'Weekly Off', thu: 'Evening', fri: 'Evening', sat: 'Weekly Off', sun: 'Weekly Off' }),
  rota('emp-012', { mon: 'Night', tue: 'Weekly Off', wed: 'Night', thu: 'Night', fri: 'Night', sat: 'Weekly Off', sun: 'Night' }),
];

/** Deliberate overlap: two nurses on Night Wed for overlap demo */
export const SHIFT_OVERLAP_COUNT = 2;

export const PENDING_LEAVE_REQUESTS = 4;
