import type { RadiologyOrder } from '../types';

export const SEED_RADIOLOGY_ORDERS: RadiologyOrder[] = [
  {
    id: 'rad-001',
    patientName: 'A.S.',
    uhid: 'NEX-2026-1001',
    orderingDoctor: 'Dr. Priya Menon',
    modality: 'X-Ray',
    scanDetails: 'Chest PA View ΓÇö rule out pneumonia',
    clinicalHistory: ['Fever 3 days', 'Productive cough', 'SpOΓéé 97% on room air'],
    status: 'Pending Capture',
  },
  {
    id: 'rad-002',
    patientName: 'R.K.',
    uhid: 'NEX-2026-1002',
    orderingDoctor: 'Dr. Arjun Das',
    modality: 'CT Scan',
    scanDetails: 'CT KUB ΓÇö renal colic protocol',
    clinicalHistory: ['Flank pain R', 'Hematuria', 'Creatinine 1.4'],
    status: 'Pending Capture',
  },
  {
    id: 'rad-003',
    patientName: 'V.P.',
    uhid: 'NEX-2026-1003',
    orderingDoctor: 'Dr. Priya Menon',
    modality: 'MRI',
    scanDetails: 'Brain MRI ΓÇö contrast, headache protocol',
    clinicalHistory: ['Chronic headache', 'No focal neuro deficit', 'Hypertension'],
    status: 'Ready for Interpretation',
    uploadedFileName: 'MRI_BRAIN_VIKRAM_DICOM.zip',
    uploadedAt: '2026-07-09T09:30:00Z',
  },
  {
    id: 'rad-004',
    patientName: 'M.I.',
    uhid: 'NEX-2026-1004',
    orderingDoctor: 'Dr. Lakshmi Nair',
    modality: 'Ultrasound',
    scanDetails: 'USG Abdomen ΓÇö hepatomegaly workup',
    clinicalHistory: ['RUQ discomfort', 'Elevated ALT', 'Diabetes Type 2'],
    status: 'Ready for Interpretation',
    uploadedFileName: 'USG_ABD_MEERA.dcm',
    uploadedAt: '2026-07-09T10:00:00Z',
  },
  {
    id: 'rad-005',
    patientName: 'S.R.',
    uhid: 'NEX-2026-1005',
    orderingDoctor: 'Dr. Arjun Das',
    modality: 'X-Ray',
    scanDetails: 'Knee AP/Lateral ΓÇö trauma',
    clinicalHistory: ['Fall yesterday', 'Swelling L knee', 'Unable to weight bear'],
    status: 'Completed',
    uploadedFileName: 'XR_KNEE_SANJAY.dcm',
    uploadedAt: '2026-07-09T07:00:00Z',
    findings: 'No acute fracture. Mild joint effusion.',
    impression: 'Soft tissue injury likely. Clinical correlation advised.',
    finalizedAt: '2026-07-09T08:00:00Z',
    finalizedBy: 'Dr. Radiologist',
    emrAppended: true,
  },
];
